name: Integracion Continua

on: [push, pull_request]

Jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    -name: Checkout del codigo
    - uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar pruebas
      run: npm test --silent

    - name: Construir proyecto
      run: npm run build